"""Init

Revision ID: ee2d8ad07b41
Revises: 6eaa6853987d
Create Date: 2023-03-08 19:55:22.012348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2d8ad07b41'
down_revision = '6eaa6853987d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
